NAME = rush-02
SRC = main.c ft_parse_dict.c separator.c print_number.c ft_strcmp.c \
	  input_nb.c ft_verif_dict_length.c main_functions.c print_tab.c

all: $(NAME)

$(NAME):
	gcc -Wall -Werror -Wextra -o $(NAME) $(SRC)

fclean:
	rm -f $(NAME)

re:
	fclean all